# Git
alias gi="git init && gac 'Initial commit'"
alias gs="git status"
alias ga="git add"
alias gcm="git commit -m"
alias gac="git add . && git commit -m"
alias gc="git checkout"
alias gcb="git checkout -b"
alias gpo="git push origin"
alias glog="git log --branches --not --remotes"
